sudo: required
services:
  - docker

before_install:
  - docker build -t jonathansunata/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true jonathansunata/docker-react npm run test -- --coverage